In [1]:
#importando as bibliotecas 
import torch
import torch_geometric
import numpy as np
import sys 
from torch_geometric.data import Data
import torch.nn.functional as F 
from torch_geometric.nn import GCNConv 
import math as mt 
import pandas as pd 
from sklearn.metrics.pairwise import euclidean_distances 

sys.path.insert(1, '/home/marina/InCi/')
from cbirdb import acbirdb,cbirdbDistMatrix,evaluator,unsuperalg,recknngraph


In [2]:
matrix = np.loadtxt('/home/marina/Documents/H/feat-matrix.txt', delimiter=",")
print(matrix.shape)
print(matrix)

(1360, 4096)
[[ 0.3737  0.0903  0.2612 ...  0.2032  0.1864  0.1939]
 [ 0.5614  0.1724  0.2699 ...  0.357   0.1149  0.1666]
 [ 0.0881  0.295   0.3034 ...  0.2992  0.4613  0.1951]
 ...
 [ 0.3688  0.2465  0.3748 ...  0.2099  0.298   0.3135]
 [ 0.3418 -0.0702  0.3993 ...  0.3181  0.0712  0.0822]
 [ 0.5089  0.5077  0.3311 ...  0.2732  0.2014  0.3501]]


In [3]:
nova_dist_matrix = euclidean_distances(matrix)
print(nova_dist_matrix.shape)
print(nova_dist_matrix)

(1360, 1360)
[[ 0.         11.15373717 11.30251275 ... 11.10669213 11.17332702
  12.66601568]
 [11.15373717  0.          9.8307264  ... 10.63833982 10.40902299
  12.40070664]
 [11.30251275  9.8307264   0.         ... 10.79422304 10.91130308
  11.86389681]
 ...
 [11.10669213 10.63833982 10.79422304 ...  0.          8.78454242
  11.1531348 ]
 [11.17332702 10.40902299 10.91130308 ...  8.78454242  0.
  12.90904463]
 [12.66601568 12.40070664 11.86389681 ... 11.1531348  12.90904463
   0.        ]]


distOriginal = np.loadtxt('/home/marina/venv/oxford17flowers-caffe-fc7_matrix.txt', delimiter=" ")
print(distOriginal.shape)
print(distOriginal)

In [4]:
with open('/home/marina/Documents/H/nova_dist_matrix.txt', 'w') as f:
    np.savetxt(f, nova_dist_matrix, fmt='%.8f')
f.close()

In [5]:
def DasProgrammeHausaufgabe(DistM, pN, classSize, numberOfClasses, pNFeatures, trPerClass, valPerClass, pK, pLR, pNNeurons, pNEpochs): 

    # máscaras 

    train_mask = [] #máscaras de treino - true = treino 
    val_mask = [] #valores das máscaras 
    test_mask = [] #máscaras de testes 
    y = [] # y = vetor de "gabarito" 

    for i in range (pN):# para cada imagem i: 
        y.append(i // classSize) # definindo o vetor de classes 
        d = i % classSize # d = resto do número da imagem dividido pela classe 
        if (d<trPerClass): # se d é menor que o número de imagens de treino por classe, então: 
            valueTr = True # treino = true 
            valueVal = False # teste = false 
        else: # d é maior ou igual ao número de imagens de treino por classe: 
            valueTr = False # treino = false 
            if (d<(valPerClass+trPerClass)): 
                valueVal = True # teste = true 
            else:
                valueVal = False #teste = false 
        valueTest = (not valueTr) and (not valueVal) 

        train_mask.append (valueTr) # criando os vetores de máscaras 
        val_mask.append(valueVal) #vetor de validação 
        test_mask.append(valueTest)

    # A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
    train_mask = torch.tensor (train_mask) #torch 
    val_mask = torch.tensor (val_mask)
    test_mask = torch.tensor (test_mask)
    y = torch.tensor (y)

    
    #-------------------------------- Feature Matrix ------------------------------------- 
    #lendo a matriz de features 

    #print ('Reading feature matrix ...')
    feat_matrix_file = '/home/marina/Documents/H/feat-matrix.txt'
    x = np.loadtxt(feat_matrix_file, delimiter= ",")
    #print(x.shape)
    x = torch.tensor(x)
    #print (x)
    
    # Indexação das Bordas 

    #arquivo lista 
    pListFile = "/home/marina/Documents/H/list.txt"
    #arquivo dist matrix
    pDSimFile = DistM #"/home/marina/venv/nova_dist_matrix.txt"


    #print ('Reading DB ...')
    db = cbirdbDistMatrix(pListFile,pDSimFile,pN)

    #print ('Making edge list ...')
    edge_index = []

    for qimg in db.getList(): #para cada imagem da lista 
        #print (qimg)
        crl = db.getRL(qimg) # mais próximos no ranked list 
        qindex = db.getIndexOf(qimg) 
        for i in range(pK): # cria arestas entre as k posições mais próximas 
            cindex = db.getIndexOf (crl[i])
            edge_index.append([qindex,cindex])

    #print(edge_index)

    #passa para o torch 
    # A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
    edge_index = torch.tensor(edge_index)
    edge_index = edge_index.t().contiguous()

    #print (edge_index)
    
    #--------------------------------- Data Object  -----------------------------------------
    #data são as informações do grafo completo (eu acho) *_* 

    #print ('Loading data object...')
    data = Data(x=x.float(), edge_index=edge_index, y=y, test_mask=test_mask, train_mask=train_mask,  val_mask=val_mask  )


    #--------------------------------- Graph Neural Network Defiition  -----------------------------------------

    # rede neural: NÃO MEXA!!!!!!!!!!

    #print ('Defining GCN model...')

    class Net(torch.nn.Module):
        def __init__(self):
            super(Net, self).__init__()
            self.conv1 = GCNConv(pNFeatures, pNNeurons) #dataset.num_node_features
            self.conv2 = GCNConv(pNNeurons, numberOfClasses) #dataset.num_classes

        def forward(self, data):
            x, edge_index = data.x, data.edge_index

            x = self.conv1(x, edge_index)
            x = F.relu(x)
            x = F.dropout(x, training=self.training)
            x = self.conv2(x, edge_index)

            return F.log_softmax(x, dim=1)



    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    #device = torch.device('cpu')
    model = Net().to(device)
    #data = dataset[0].to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=pLR, weight_decay=5e-4)



    print ('Training...')

    model.train() # treinando com a rede neural 
    for epoch in range(pNEpochs):	
        #print("Training epoch: ", epoch)
        optimizer.zero_grad()
        out = model(data)
        loss = F.nll_loss(out[data.train_mask], data.y[data.train_mask])
        loss.backward()
        optimizer.step()


    # aqui ele avalia o modelo, com base nas máscaras de teste e treino que definimos no começo     
    model.eval()
    _, pred = model(data).max(dim=1)
    correct = float (pred[data.test_mask].eq(data.y[data.test_mask]).sum().item())
    acc = correct / pN #data.test_mask.sum().item() # esse acc é o mesmo da soccer? é um descritor? 

    #print('Accuracy: {:.4f}'.format(acc)) 
    return(acc)

In [6]:
# informações do dataset
pN = 1360 
classSize = 80
numberOfClasses = 17

pNFeatures = 4096 # número de features 

# parâmetros 
trPerClass = 15 #treinamento por classe 
valPerClass = 0*trPerClass #valores por classe 

pK = 35 # número de vizinhos mais próximos (serve para gerar o grafo)
pLR = 0.001 # learning rate: o quão rápido os pesos são atualizados (não mexer)
pNNeurons = 32 # quantidade de neurônios nas camadas intermediárias (serve para otimizar)
pNEpochs = 200 # quantidade de interações de treinamento a cada época (calcula e ajusta os pesos)
# época = rodada de ajustes de pesos 

DistM = "/home/marina/Documents/H/nova_dist_matrix.txt"

DasProgrammeHausaufgabe(DistM, pN, classSize, numberOfClasses, pNFeatures, trPerClass, valPerClass, pK, pLR, pNNeurons, pNEpochs)


Training...


0.04779411764705882